require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AppliancesController do

  # This should return the minimal set of attributes required to create a valid
  # Appliance. As you add validations to Appliance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "storeNumbre" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AppliancesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all appliances as @appliances" do
      appliance = Appliance.create! valid_attributes
      get :index, {}, valid_session
      assigns(:appliances).should eq([appliance])
    end
  end

  describe "GET show" do
    it "assigns the requested appliance as @appliance" do
      appliance = Appliance.create! valid_attributes
      get :show, {:id => appliance.to_param}, valid_session
      assigns(:appliance).should eq(appliance)
    end
  end

  describe "GET new" do
    it "assigns a new appliance as @appliance" do
      get :new, {}, valid_session
      assigns(:appliance).should be_a_new(Appliance)
    end
  end

  describe "GET edit" do
    it "assigns the requested appliance as @appliance" do
      appliance = Appliance.create! valid_attributes
      get :edit, {:id => appliance.to_param}, valid_session
      assigns(:appliance).should eq(appliance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Appliance" do
        expect {
          post :create, {:appliance => valid_attributes}, valid_session
        }.to change(Appliance, :count).by(1)
      end

      it "assigns a newly created appliance as @appliance" do
        post :create, {:appliance => valid_attributes}, valid_session
        assigns(:appliance).should be_a(Appliance)
        assigns(:appliance).should be_persisted
      end

      it "redirects to the created appliance" do
        post :create, {:appliance => valid_attributes}, valid_session
        response.should redirect_to(Appliance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved appliance as @appliance" do
        # Trigger the behavior that occurs when invalid params are submitted
        Appliance.any_instance.stub(:save).and_return(false)
        post :create, {:appliance => { "storeNumbre" => "invalid value" }}, valid_session
        assigns(:appliance).should be_a_new(Appliance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Appliance.any_instance.stub(:save).and_return(false)
        post :create, {:appliance => { "storeNumbre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested appliance" do
        appliance = Appliance.create! valid_attributes
        # Assuming there are no other appliances in the database, this
        # specifies that the Appliance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Appliance.any_instance.should_receive(:update).with({ "storeNumbre" => "1" })
        put :update, {:id => appliance.to_param, :appliance => { "storeNumbre" => "1" }}, valid_session
      end

      it "assigns the requested appliance as @appliance" do
        appliance = Appliance.create! valid_attributes
        put :update, {:id => appliance.to_param, :appliance => valid_attributes}, valid_session
        assigns(:appliance).should eq(appliance)
      end

      it "redirects to the appliance" do
        appliance = Appliance.create! valid_attributes
        put :update, {:id => appliance.to_param, :appliance => valid_attributes}, valid_session
        response.should redirect_to(appliance)
      end
    end

    describe "with invalid params" do
      it "assigns the appliance as @appliance" do
        appliance = Appliance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Appliance.any_instance.stub(:save).and_return(false)
        put :update, {:id => appliance.to_param, :appliance => { "storeNumbre" => "invalid value" }}, valid_session
        assigns(:appliance).should eq(appliance)
      end

      it "re-renders the 'edit' template" do
        appliance = Appliance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Appliance.any_instance.stub(:save).and_return(false)
        put :update, {:id => appliance.to_param, :appliance => { "storeNumbre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested appliance" do
      appliance = Appliance.create! valid_attributes
      expect {
        delete :destroy, {:id => appliance.to_param}, valid_session
      }.to change(Appliance, :count).by(-1)
    end

    it "redirects to the appliances list" do
      appliance = Appliance.create! valid_attributes
      delete :destroy, {:id => appliance.to_param}, valid_session
      response.should redirect_to(appliances_url)
    end
  end

end
