require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LinuxUsersController do

  # This should return the minimal set of attributes required to create a valid
  # LinuxUser. As you add validations to LinuxUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LinuxUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all linux_users as @linux_users" do
      linux_user = LinuxUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:linux_users).should eq([linux_user])
    end
  end

  describe "GET show" do
    it "assigns the requested linux_user as @linux_user" do
      linux_user = LinuxUser.create! valid_attributes
      get :show, {:id => linux_user.to_param}, valid_session
      assigns(:linux_user).should eq(linux_user)
    end
  end

  describe "GET new" do
    it "assigns a new linux_user as @linux_user" do
      get :new, {}, valid_session
      assigns(:linux_user).should be_a_new(LinuxUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested linux_user as @linux_user" do
      linux_user = LinuxUser.create! valid_attributes
      get :edit, {:id => linux_user.to_param}, valid_session
      assigns(:linux_user).should eq(linux_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LinuxUser" do
        expect {
          post :create, {:linux_user => valid_attributes}, valid_session
        }.to change(LinuxUser, :count).by(1)
      end

      it "assigns a newly created linux_user as @linux_user" do
        post :create, {:linux_user => valid_attributes}, valid_session
        assigns(:linux_user).should be_a(LinuxUser)
        assigns(:linux_user).should be_persisted
      end

      it "redirects to the created linux_user" do
        post :create, {:linux_user => valid_attributes}, valid_session
        response.should redirect_to(LinuxUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved linux_user as @linux_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        LinuxUser.any_instance.stub(:save).and_return(false)
        post :create, {:linux_user => { "user" => "invalid value" }}, valid_session
        assigns(:linux_user).should be_a_new(LinuxUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LinuxUser.any_instance.stub(:save).and_return(false)
        post :create, {:linux_user => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested linux_user" do
        linux_user = LinuxUser.create! valid_attributes
        # Assuming there are no other linux_users in the database, this
        # specifies that the LinuxUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LinuxUser.any_instance.should_receive(:update).with({ "user" => "MyString" })
        put :update, {:id => linux_user.to_param, :linux_user => { "user" => "MyString" }}, valid_session
      end

      it "assigns the requested linux_user as @linux_user" do
        linux_user = LinuxUser.create! valid_attributes
        put :update, {:id => linux_user.to_param, :linux_user => valid_attributes}, valid_session
        assigns(:linux_user).should eq(linux_user)
      end

      it "redirects to the linux_user" do
        linux_user = LinuxUser.create! valid_attributes
        put :update, {:id => linux_user.to_param, :linux_user => valid_attributes}, valid_session
        response.should redirect_to(linux_user)
      end
    end

    describe "with invalid params" do
      it "assigns the linux_user as @linux_user" do
        linux_user = LinuxUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LinuxUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => linux_user.to_param, :linux_user => { "user" => "invalid value" }}, valid_session
        assigns(:linux_user).should eq(linux_user)
      end

      it "re-renders the 'edit' template" do
        linux_user = LinuxUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LinuxUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => linux_user.to_param, :linux_user => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested linux_user" do
      linux_user = LinuxUser.create! valid_attributes
      expect {
        delete :destroy, {:id => linux_user.to_param}, valid_session
      }.to change(LinuxUser, :count).by(-1)
    end

    it "redirects to the linux_users list" do
      linux_user = LinuxUser.create! valid_attributes
      delete :destroy, {:id => linux_user.to_param}, valid_session
      response.should redirect_to(linux_users_url)
    end
  end

end
