require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SituationsController do

  # This should return the minimal set of attributes required to create a valid
  # Situation. As you add validations to Situation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SituationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all situations as @situations" do
      situation = Situation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:situations).should eq([situation])
    end
  end

  describe "GET show" do
    it "assigns the requested situation as @situation" do
      situation = Situation.create! valid_attributes
      get :show, {:id => situation.to_param}, valid_session
      assigns(:situation).should eq(situation)
    end
  end

  describe "GET new" do
    it "assigns a new situation as @situation" do
      get :new, {}, valid_session
      assigns(:situation).should be_a_new(Situation)
    end
  end

  describe "GET edit" do
    it "assigns the requested situation as @situation" do
      situation = Situation.create! valid_attributes
      get :edit, {:id => situation.to_param}, valid_session
      assigns(:situation).should eq(situation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Situation" do
        expect {
          post :create, {:situation => valid_attributes}, valid_session
        }.to change(Situation, :count).by(1)
      end

      it "assigns a newly created situation as @situation" do
        post :create, {:situation => valid_attributes}, valid_session
        assigns(:situation).should be_a(Situation)
        assigns(:situation).should be_persisted
      end

      it "redirects to the created situation" do
        post :create, {:situation => valid_attributes}, valid_session
        response.should redirect_to(Situation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved situation as @situation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Situation.any_instance.stub(:save).and_return(false)
        post :create, {:situation => { "name" => "invalid value" }}, valid_session
        assigns(:situation).should be_a_new(Situation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Situation.any_instance.stub(:save).and_return(false)
        post :create, {:situation => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested situation" do
        situation = Situation.create! valid_attributes
        # Assuming there are no other situations in the database, this
        # specifies that the Situation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Situation.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => situation.to_param, :situation => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested situation as @situation" do
        situation = Situation.create! valid_attributes
        put :update, {:id => situation.to_param, :situation => valid_attributes}, valid_session
        assigns(:situation).should eq(situation)
      end

      it "redirects to the situation" do
        situation = Situation.create! valid_attributes
        put :update, {:id => situation.to_param, :situation => valid_attributes}, valid_session
        response.should redirect_to(situation)
      end
    end

    describe "with invalid params" do
      it "assigns the situation as @situation" do
        situation = Situation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Situation.any_instance.stub(:save).and_return(false)
        put :update, {:id => situation.to_param, :situation => { "name" => "invalid value" }}, valid_session
        assigns(:situation).should eq(situation)
      end

      it "re-renders the 'edit' template" do
        situation = Situation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Situation.any_instance.stub(:save).and_return(false)
        put :update, {:id => situation.to_param, :situation => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested situation" do
      situation = Situation.create! valid_attributes
      expect {
        delete :destroy, {:id => situation.to_param}, valid_session
      }.to change(Situation, :count).by(-1)
    end

    it "redirects to the situations list" do
      situation = Situation.create! valid_attributes
      delete :destroy, {:id => situation.to_param}, valid_session
      response.should redirect_to(situations_url)
    end
  end

end
